### ISSUE TITLE
Why is this project still in alpha?

### ISSUE THREAD

**Issue by dometto** [diddi-/flask-seeder#2]
@diddi- thanks for working on this project! Could you elaborate on its status? That is, why is the current version still in alpha? Are any essential features still missing, or are there any other reasons for not using the project at the moment?

**Comment by diddi-** [comment]
Hey! The reason it's in alpha is just because I wanted some time to use it properly to catch major bugs and collect general feedback. Now that it's been out in the wild for a while I think it's a good time to consider it stable :) 

I'll take it out of alpha!

**Comment by diddi-** [comment]
Thanks for opening this issue, [version 1.0 is now on pypi](https://pypi.org/project/Flask-Seeder/)! 🎉
