### ISSUE TITLE
The pip version isn't updated

### ISSUE THREAD

**Issue by CarlosFR4** [diddi-/flask-seeder#4]
I tried the project but the code used to [sort the seeders](https://github.com/diddi-/flask-seeder/blob/master/flask_seeder/cli.py) by priority isn't in the pip version.
Same with the wheel file.

**Comment by diddi-** [comment]
Hey, Flask-Seeder v1.1.0 is now released on PyPi!

**Comment by CarlosFR4** [comment]
Thanks! Already downloaded it xD
