### ISSUE TITLE
Error when db and app are configured separately

### ISSUE THREAD

**Issue by twelvelabs** [diddi-/flask-seeder#5]
When setting up `FlaskSeeder` in the following way, the `db` instance does not get configured correctly, and attempts to use `flask seed run` fail.

```python
# database.py
db = SQLAlchemy()
seeder = FlaskSeeder(db=db)

# __init__.py
from database import db, seeder
app = Flask(__name__)
db.init_app(app)
seeder.init_app(app)
```

The error:

```
$ flask seed run
Running database seeders
DefaultSeeder...	[OK]
Committing to database!
[2020-02-21 17:25:18,543] ERROR in logging: 'NoneType' object has no attribute 'session'
```

It looks to me like it's due to:

https://github.com/diddi-/flask-seeder/blob/1dbd6dd6d9a627c6865f0a20df7e29e928bc0c72/flask_seeder/__init__.py#L53

Which should be `SeedConfig(self.db)` rather than just `db`, correct?

**Comment by diddi-** [comment]
Hey, just want to let you know I've seen this and thanks for reporting. I will look into it as soon as I find time in the next couple of days :)

**Comment by diddi-** [comment]
You are very much correct in that it should use `self.db`. I've release version `v1.1.1` of FlaskSeeder now which includes this fix.

Thanks!
